# Generated by Django 4.1.7 on 2023-03-17 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_flows", "0025_alter_flowstagebinding_evaluate_on_plan_and_more"),
        ("authentik_core", "0026_alter_propertymapping_name_alter_provider_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="invalidation_flow",
            field=models.ForeignKey(
                default=None,
                help_text="Flow used ending the session from a provider.",
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="provider_invalidation",
                to="authentik_flows.flow",
            ),
        ),
    ]
